spring:
  profiles:
    active: dev
    include:
      - feign
      - sentinel
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 192.168.0.31:8848
      config:
        namespace: ${spring.profiles.active:public}
server:
  port: 8000

logging:
  level:
    com.deltav.order.feign: debug

---
spring:
  config:
    import:
      - nacos:service-order.yml?group=SERVICE_ORDER
      - nacos:database.yml?group=SERVICE_ORDER
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:service-order.yml?group=SERVICE_ORDER
      - nacos:database.yml?group=SERVICE_ORDER
      - nacos:test.yml?group=SERVICE_ORDER
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:service-order.yml?group=SERVICE_ORDER
      - nacos:database.yml?group=SERVICE_ORDER
      - nacos:prod.yml?group=SERVICE_ORDER
    activate:
      on-profile: prod
