server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  client:
    config:
      CLOUD-PAYMENT-SERVICE:
        logger-level: full

logging:
  level:
    com.deltav.cloudfeignorder80.service.PaymentFeignService: debug